"""
Django settings for user_management project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-q+daqjb$x0v=mi_ou(y&0b!_m8vr$tjs!wo6tb^7e*c=w9llze'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'enroll',
    'vendor',
    'ckeditor',
    'vendor_api',
    'store',
    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'user_management.middleware.ajax_login_required_middleware.AjaxLoginRequiredMiddleware',
    

]


ROOT_URLCONF = 'user_management.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [r"/home/spxlpt193/Desktop/task/user_management/enroll/templates/enroll"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'user_management.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',  # Specifies PostgreSQL as the backend
        'NAME': 'postgres',                      # The name of your database
        'USER': 'postgres',                          # Your PostgreSQL username
        'PASSWORD': 'Sparx@1234',
        'HOST': 'localhost',                       # Database server (use 'localhost' if running locally)
        'PORT': '5432',                            # Default PostgreSQL port (can be changed if necessary)
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'enroll/static'),
]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Static files configuration
STATICFILES_IGNORE_PATTERNS = [
    r'.*\.map$',  # Ignore all source map files
]

# Media files (Uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Debug settings
DEBUG = True

# Session settings
SESSION_COOKIE_AGE = 600 # 10 min
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_SAVE_EVERY_REQUEST = True

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'email-smtp.us-east-2.amazonaws.com'  # SMTP server
EMAIL_PORT = 587  # Port for TLS (587) or 465 for SSL
EMAIL_USE_TLS = True  # Use TLS encryption
EMAIL_HOST_USER = 'AKIAV5LTCJN4N5WVEJU2' # Your SMTP username
EMAIL_HOST_PASSWORD = "BPS/3TKyw88MVCw7ASfgvYAeoReuzs8NHXvSkmk7QEco"# Your SMTP password
DEFAULT_FROM_EMAIL = 'no-reply@thesparxitsolutions.com'  # Sender email address

# AUTH_USER_MODEL = 'enroll.AuthLogin'
LOGIN_URL = '/store/user_login/'

