# Generated by Django 4.0.7 on 2025-02-20 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childsubcategory',
            name='feature_category',
            field=models.BooleanField(default=True),
        ),
    ]
