# Generated by Django 4.0.7 on 2025-02-21 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0004_remove_banner_banner_image_remove_banner_caption_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bannerimage',
            old_name='image',
            new_name='images',
        ),
    ]
