# Generated by Django 4.0.7 on 2025-02-21 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0007_remove_bannerimage_link_banner_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='link',
        ),
        migrations.AddField(
            model_name='bannerimage',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
