# Generated by Django 4.0.7 on 2025-03-17 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0011_brand_meta_description_brand_meta_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='image',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='long_description',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='meta_title',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='short_description',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='updated_at',
        ),
    ]
