# Generated by Django 4.0.7 on 2025-03-17 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0012_remove_tag_created_at_remove_tag_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='enroll.category'),
        ),
        migrations.AddField(
            model_name='brand',
            name='child_subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='enroll.childsubcategory'),
        ),
        migrations.AddField(
            model_name='brand',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='enroll.subcategory'),
        ),
        migrations.AddField(
            model_name='tag',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='enroll.category'),
        ),
        migrations.AddField(
            model_name='tag',
            name='child_subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='enroll.childsubcategory'),
        ),
        migrations.AddField(
            model_name='tag',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='enroll.subcategory'),
        ),
    ]
