# Generated by Django 4.0.7 on 2025-03-24 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0013_brand_category_brand_child_subcategory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecificationField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='enroll.category')),
            ],
        ),
    ]
