# Generated by Django 4.0.7 on 2025-03-25 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0014_specificationfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('input_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('select', 'Dropdown')], max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='enroll.category')),
            ],
        ),
        migrations.CreateModel(
            name='SpecificationChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('specification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='enroll.specification')),
            ],
        ),
        migrations.DeleteModel(
            name='SpecificationField',
        ),
    ]
