# Generated by Django 4.0.7 on 2025-04-01 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0015_specification_specificationchoice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('display_name', models.CharField(max_length=255)),
                ('default_value', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, choices=[('Textbox', 'Textbox'), ('Upload', 'Upload img/pdf'), ('Dropdown', 'Dropdown')], max_length=50, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='attributes',
            field=models.ManyToManyField(blank=True, related_name='categories', to='enroll.attribute'),
        ),
        migrations.AddField(
            model_name='childsubcategory',
            name='attributes',
            field=models.ManyToManyField(blank=True, related_name='child_subcategories', to='enroll.attribute'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='attributes',
            field=models.ManyToManyField(blank=True, related_name='subcategories', to='enroll.attribute'),
        ),
    ]
