# Generated by Django 4.0.7 on 2025-03-27 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0016_attribute'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attribute',
            old_name='variant',
            new_name='display_name',
        ),
        migrations.AddField(
            model_name='attribute',
            name='default_value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='type',
            field=models.CharField(blank=True, choices=[('Textbox', 'Textbox'), ('Upload', 'Upload img/pdf'), ('Dropdown', 'Dropdown')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Inactive', max_length=50),
        ),
    ]
