# Generated by Django 4.0.7 on 2025-03-27 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0017_rename_variant_attribute_display_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=50),
        ),
    ]
