# Generated by Django 4.0.7 on 2025-03-28 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0019_attribute_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribute',
            name='categories',
        ),
        migrations.AddField(
            model_name='category',
            name='attributes',
            field=models.ManyToManyField(blank=True, related_name='categories', to='enroll.attribute'),
        ),
    ]
