# Generated by Django 4.0.7 on 2025-03-28 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0019_attribute_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribute',
            name='categories',
        ),
        migrations.AddField(
            model_name='attribute',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='enroll.category'),
        ),
    ]
