# Generated by Django 4.0.7 on 2025-03-28 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0020_remove_attribute_categories_attribute_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribute',
            name='category',
        ),
        migrations.AddField(
            model_name='category',
            name='attributes',
            field=models.ManyToManyField(blank=True, related_name='categories', to='enroll.attribute'),
        ),
    ]
