# Generated by Django 4.0.7 on 2025-03-28 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0020_remove_attribute_categories_category_attributes'),
        ('enroll', '0021_remove_attribute_category_category_attributes'),
    ]

    operations = [
    ]
