# Generated by Django 4.0.7 on 2025-04-01 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0016_attribute_category_attributes_and_more'),
        ('enroll', '0022_merge_20250328_0949'),
    ]

    operations = [
    ]
